#!/command/with-contenv bash
. "/usr/local/bin/logger"
# ==============================================================================
# hikvision
# Runs hikvision
# ==============================================================================

echo "Waiting for ZoneMinder to start" | info
s6-svwait -U /run/service/zoneminder

echo "Starting hikvision..." | info

exec fdmove -c 2 1 \
  /config/zmscript.sh
